/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ADC_BASE_ADDR		0x40012000UL
#define ADC_CR1_REG_OFFSET	0x04UL
#define ADC_CR1_REG_ADDR	(ADC_BASE_ADDR + ADC_CR1_REG_OFFSET)

#define RCC_BASE_ADDR		0x40023800UL
#define RCC_APB2_ENR_OFFSET	0x44UL
#define RCC_APBR_ENR_ADDR	(RCC_BASE_ADDR + RCC_APB2_ENR_OFFSET)


int main(void)
{
	uint32_t *pRccApb2EnrReg = (uint32_t *)RCC_APBR_ENR_ADDR;
	uint32_t *pAdcCr1Reg = (uint32_t *)ADC_CR1_REG_ADDR;

	// 1. Enable ADC clock in RCC.
	*pRccApb2EnrReg |= (1 << 8);

	// 2. Modify ADC register to enable scanning.
	*pAdcCr1Reg |= (1 << 8);

    /* Loop forever */
	for(;;);
}
